### ISSUE TITLE
Write checksums to plugins.yaml

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#309]
We document that we follow https://en.wikipedia.org/wiki/Trust_on_first_use

When we fetch a plugin binary, if there are no checksums for the current platform, we should calculate a checksum of the file we just fetched and edit the plugins.yaml file to add one.
If there is a checksum for the current platform, we verify that the download matches.

Example:

User writes

```
- name: plugin-aspect-pro
  # Cloudflare CDN that is backed by http://static.aspect.build.s3-website.us-east-2.amazonaws.com/cli
  from: https://static.aspect.build/cli
  # Uncomment one of the following when developing plugins locally
  # from: //cli/pro-plugin:pro-plugin
  # from: ./bazel-bin/cli/pro-plugin/pro-plugin_/pro-plugin
  version: v0.10.0
```

then after running on linux_x86

```
- name: plugin-aspect-pro
  # Cloudflare CDN that is backed by http://static.aspect.build.s3-website.us-east-2.amazonaws.com/cli
  from: https://static.aspect.build/cli
  # Uncomment one of the following when developing plugins locally
  # from: //cli/pro-plugin:pro-plugin
  # from: ./bazel-bin/cli/pro-plugin/pro-plugin_/pro-plugin
  version: v0.10.0
  checksums:
    - linux_x86:
      deadbeef
```

They check the file in, then their coworker runs on darwin_arm:

```
- name: plugin-aspect-pro
  # Cloudflare CDN that is backed by http://static.aspect.build.s3-website.us-east-2.amazonaws.com/cli
  from: https://static.aspect.build/cli
  # Uncomment one of the following when developing plugins locally
  # from: //cli/pro-plugin:pro-plugin
  # from: ./bazel-bin/cli/pro-plugin/pro-plugin_/pro-plugin
  version: v0.10.0
  checksums:
    - linux_x86:
      deadbeef
    - darwin_arm:
      12345678
```
