### ISSUE TITLE
[FR]: support authentication for private plugin download destinations

### ISSUE THREAD

**Issue by kzadorozhny** [aspect-build/aspect-cli#833]
### What is the current behavior?

Cli startup fails to download plugin binaries that require authentication.

```yaml
plugins:
  - name: bigcorp
    from: https://artifactory.bigcorp.com/artifactory/generic-bigcorp-release/bigcorp-plugin
    version: v0.10.0
```

### Describe the feature

Consult `.netrc` file for private plugins artifacts downloads.
